interface Simple_Server
{
  typedef float HeadPoseArray[7];

  oneway void send_data(in long microsecond, in HeadPoseArray headpose);

  typedef octet pixels[11059200];

  pixels sendImageData();
    
  

};
