interface Simple_Server
{
  typedef float HeadPoseArray[7];

  oneway void send_data(in long microsecond, in HeadPoseArray headpose);

  typedef sequence<octet, 700000> pixels;
  typedef sequence<octet, 100000> header;

  pixels sendImageData();
  header sendHeaderData();

  long sendJpegSize();
  long sendHeaderSize();

};
